# Generated by Django 6.0.3 on 2026-10-03 15:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_grant_cashier_appointment_visibility'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0006_branch_is_main_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='accounts_user_email_ci_unique'),
        ),
    ]
