# Generated by Django 6.0.3 on 2026-10-03 15:31

from datetime import datetime, timezone

from django.db import migrations, models


def mark_legacy_emails_unverified(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    rollout_time = datetime(2026, 10, 3, 15, 1, tzinfo=timezone.utc)
    User.objects.filter(
        email_verified=True,
        date_joined__lt=rollout_time,
    ).exclude(email='').update(email_verified=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_legacy_emails_unverified,
            migrations.RunPython.noop,
        ),
    ]
