# Generated by Django 6.0.3 on 2026-10-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner_account_deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='owner_deactivation_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='owner_deactivation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
