"""
Django settings for FMHANIMALCLINIC project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import warnings
from pathlib import Path


def _load_environment_file(env_path):
    """Load key/value pairs from a .env file into os.environ without overriding existing values."""
    if not env_path.exists():
        return

    with open(env_path, encoding='utf-8') as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line or line.startswith('#'):
                continue

            if line.startswith('export '):
                line = line[7:].strip()

            if '=' not in line:
                continue

            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")

            if key:
                os.environ.setdefault(key, value)


# Suppress naive datetime warnings caused by Django admin internals querying
# DateTimeField (e.g. Pet.created_at) while USE_TZ=True is active.
warnings.filterwarnings(
    'ignore',
    message=r'.*received a naive datetime.*',
    category=RuntimeWarning,
    module=r'django\.db\.models\.fields',
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
env_path = BASE_DIR / '.env'
_load_environment_file(env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get(
    'ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'landing',
    'accounts',
    'branches',
    'patients',
    'appointments',
    'records',
    'inventory',
    'billing',
    'employees',
    'notifications',
    'payroll',
    'pos.apps.PosConfig',
    'reports',
    'utils',
    'settings',
    'diagnostics',
    'disease_geo_mapping',
    'inquiries',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'settings.middleware.MaintenanceModeMiddleware',
    'settings.middleware.SessionTimeoutMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FMHANIMALCLINIC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.unread_notifications',
                'patients.context_processors.patient_stats.patient_stats',
                'settings.context_processors.clinic_settings',
                'settings.context_processors.landing_content',
                'inquiries.context_processors.new_inquiry_count',
                'settings.context_processors.legal_documents',
                'accounts.context_processors.navigation_modules',
            ],
        },
    },
]

WSGI_APPLICATION = 'FMHANIMALCLINIC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.environ.get('DB_ENGINE', 'postgresql').lower()

if DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'fmhclinic'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    raise ValueError('This project is configured for PostgreSQL only. Set DB_ENGINE=postgresql.')


def _ensure_postgres_database():
    """Create the configured PostgreSQL database if it does not already exist."""
    db_config = DATABASES.get('default', {})
    if db_config.get('ENGINE') != 'django.db.backends.postgresql':
        return

    db_name = db_config.get('NAME')
    if not db_name:
        return

    try:
        import psycopg
    except ImportError:
        return

    admin_db_name = os.environ.get('DB_ADMIN_NAME', 'postgres')
    connection_kwargs = {
        'dbname': admin_db_name,
        'user': db_config.get('USER', 'postgres'),
        'password': db_config.get('PASSWORD', 'postgres'),
        'host': db_config.get('HOST', 'localhost'),
        'port': db_config.get('PORT', '5432'),
    }

    try:
        with psycopg.connect(**connection_kwargs) as connection:
            connection.autocommit = True
            with connection.cursor() as cursor:
                cursor.execute(
                    'SELECT 1 FROM pg_database WHERE datname = %s',
                    (db_name,),
                )
                if cursor.fetchone() is None:
                    safe_db_name = db_name.replace('"', '""')
                    cursor.execute(f'CREATE DATABASE "{safe_db_name}"')
    except psycopg.OperationalError:
        # Let Django surface the original connection error if the server is unavailable.
        return


_ensure_postgres_database()


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True
USE_L10N = True

USE_TZ = True

# Enable thousands grouping globally (for floatformat)
USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
AUTH_USER_MODEL = 'accounts.User'

# Session settings: expire after 24 hours of inactivity.
SESSION_COOKIE_AGE = 24 * 60 * 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Media files (uploads saved into static/ so images stay in one place)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'static'

# Email settings
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'noreply@fmhanimalclinic.com')

# GROQ API settings for AI Diagnostics
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')

# Ensure logs directory exists
log_dir = BASE_DIR / 'logs'
log_dir.mkdir(exist_ok=True)

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'fmh': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}


# =============================================================================
# Email Configuration (Gmail SMTP for OTP)
# =============================================================================

# Use console backend for development (prints emails to terminal)
# Switch to SMTP backend for production
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get(
    'EMAIL_HOST_USER', 'noreply@fmhanimalclinic.com')
