# Generated by Django 6.0.3 on 2026-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_rename_records_med_medical_7b8ea0_idx_records_med_medical_18ee7c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfile',
            name='laboratory_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
