# Generated by Django 6.0.3 on 2026-10-03 16:38

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_inactive_staff(apps, schema_editor):
    StaffMember = apps.get_model('employees', 'StaffMember')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    for staff in StaffMember.objects.filter(is_active=False, inactive_since__isnull=True).iterator():
        StaffMember.objects.filter(pk=staff.pk).update(
            inactive_since=staff.updated_at or timezone.now()
        )
        if staff.user_id:
            User.objects.filter(
                pk=staff.user_id,
                is_active=True,
                is_superuser=False,
            ).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_staffmember_default_staff_allowance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='inactive_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_inactive_staff, migrations.RunPython.noop),
    ]
